name: base
channels:
  - pytorch
  - rapidsai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - absl-py=2.1.0=pyhd8ed1ab_0
  - aiohttp=3.9.3=py310h2372a71_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - archspec=0.2.3=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.7.11=h0b4cabd_1
  - aws-c-cal=0.6.9=h14ec70c_3
  - aws-c-common=0.9.12=hd590300_0
  - aws-c-compression=0.2.17=h572eabf_8
  - aws-c-event-stream=0.4.1=h97bb272_2
  - aws-c-http=0.8.0=h9129f04_2
  - aws-c-io=0.14.0=hf8f278a_1
  - aws-c-mqtt=0.10.1=h2b97f5f_0
  - aws-c-s3=0.4.9=hca09fc5_0
  - aws-c-sdkutils=0.1.13=h572eabf_1
  - aws-checksums=0.1.17=h572eabf_7
  - aws-crt-cpp=0.26.0=h04327c0_8
  - aws-sdk-cpp=1.11.210=hba3e011_10
  - blinker=1.7.0=pyhd8ed1ab_0
  - bokeh=3.4.0=pyhd8ed1ab_0
  - boltons=24.0.0=pyhd8ed1ab_0
  - brotli=1.0.9=he6710b0_2
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.3.11=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.3=pyhd8ed1ab_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py310h2fee648_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - conda=24.3.0=py310hff52083_0
  - conda-libmamba-solver=24.1.0=pyhd8ed1ab_0
  - conda-package-handling=2.2.0=pyh38be061_0
  - conda-package-streaming=0.9.0=pyhd8ed1ab_0
  - contourpy=1.2.1=py310hd41b1e2_0
  - cryptography=42.0.5=py310h75e40e8_0
  - cuda-cccl=12.4.127=0
  - cuda-cccl_linux-64=12.0.90=ha770c72_1
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cudart-dev_linux-64=12.0.107=h59595ed_8
  - cuda-cudart-static=12.0.107=hd3aeb46_8
  - cuda-cudart-static_linux-64=12.0.107=h59595ed_8
  - cuda-cudart_linux-64=12.0.107=h59595ed_8
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvcc-dev_linux-64=12.0.76=ha770c72_1
  - cuda-nvcc-impl=12.0.76=h59595ed_1
  - cuda-nvcc-tools=12.0.76=h59595ed_1
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-profiler-api=12.0.76=ha770c72_0
  - cuda-python=12.4.0=py310h9f9f131_1
  - cuda-runtime=12.1.0=0
  - cuda-version=12.0=hffde075_3
  - cudf=24.02.02=cuda12_py310_240227_gdd34fdbe35_0
  - cudnn=8.9.7.29=h092f7fd_3
  - cuml=24.02.00=cuda12_py310_240213_geb50e481d_0
  - cupy=13.0.0=py310h7aad9d2_3
  - cupy-core=13.0.0=py310had4011e_3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.3=py310h2372a71_0
  - dask=2024.1.1=pyhd8ed1ab_0
  - dask-core=2024.1.1=pyhd8ed1ab_0
  - dask-cuda=24.02.00=py310_240212_g96bedbc_0
  - dask-cudf=24.02.02=cuda12_py310_240227_gdd34fdbe35_0
  - distributed=2024.1.1=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_0
  - dlpack=0.5=h9c3ff4c_0
  - fastrlock=0.8.2=py310hc6cd4ac_2
  - filelock=3.13.3=pyhd8ed1ab_0
  - flatbuffers=23.5.26=h59595ed_1
  - fmt=10.2.1=h00ab1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h267a509_2
  - frozenlist=1.4.1=py310h2372a71_0
  - fsspec=2024.3.1=pyhca7485f_0
  - gast=0.5.4=pyhd8ed1ab_0
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.1=h0b41bf4_3
  - glog=0.6.0=h6f12383_0
  - gmock=1.14.0=ha770c72_1
  - gmp=6.3.0=h59595ed_1
  - gmpy2=2.1.2=py310h3ec546c_1
  - google-auth=2.29.0=pyhca7485f_0
  - google-auth-oauthlib=1.2.0=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpcio=1.59.3=py310h1b8f574_0
  - gtest=1.14.0=h00ab1b0_1
  - h5py=3.10.0=nompi_py310h65828d5_101
  - hdf5=1.14.3=nompi_h4f84152_100
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - joblib=1.4.0=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py310hff52083_3
  - keras=2.15.0=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.21.2=h659d440_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libaec=1.1.3=h59595ed_0
  - libarchive=3.7.2=h2aa1ff5_1
  - libarrow=14.0.2=h84dd17c_3_cpu
  - libarrow-acero=14.0.2=h59595ed_3_cpu
  - libarrow-dataset=14.0.2=h59595ed_3_cpu
  - libarrow-flight=14.0.2=h120cb0d_3_cpu
  - libarrow-flight-sql=14.0.2=h61ff412_3_cpu
  - libarrow-gandiva=14.0.2=hacb8726_3_cpu
  - libarrow-substrait=14.0.2=h61ff412_3_cpu
  - libblas=3.9.0=22_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=22_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcudf=24.02.02=cuda12_240227_gdd34fdbe35_0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcufile-dev=1.9.1.3=0
  - libcuml=24.02.00=cuda12_240213_geb50e481d_0
  - libcumlprims=24.02.00=cuda12_240213_g0e32024_0
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcurl=8.7.1=hca28451_0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libgoogle-cloud=2.12.0=h5206363_4
  - libgrpc=1.59.3=hd6c4280_0
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - libkvikio=24.02.01=cuda12_240226_gfe01c15_0
  - liblapack=3.9.0=22_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libllvm15=15.0.7=hb3ce162_4
  - libmagma=2.7.2=h173bb3b_2
  - libmagma_sparse=2.7.2=h173bb3b_3
  - libmamba=1.5.8=had39da4_0
  - libmambapy=1.5.8=py310h39ff949_0
  - libnghttp2=1.58.0=h47da74e_1
  - libnl=3.9.0=hd590300_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libparquet=14.0.2=h352af49_3_cpu
  - libpng=1.6.43=h2797004_0
  - libprotobuf=4.24.4=hf27288f_0
  - libraft=24.02.00=cuda12_240212_g698d6c7b_0
  - libraft-headers=24.02.00=cuda12_240212_g698d6c7b_0
  - libraft-headers-only=24.02.00=cuda12_240212_g698d6c7b_0
  - libre2-11=2023.09.01=h7a70373_1
  - librmm=24.02.00=cuda12_240212_g09b406c1_0
  - libsolv=0.7.28=hfc55251_2
  - libsqlite=3.45.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.6.0=h1dd3fc0_3
  - libtorch=2.1.2=cuda120_h86db2e7_300
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.48.0=hd590300_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.6=h232c23b_1
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=18.1.2=h4dfa4b3_0
  - llvmlite=0.42.0=py310h1b8f574_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py310h350c4a5_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - magma=2.7.2=h51420fd_3
  - mamba=1.5.8=py310h51d5547_0
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py310h2372a71_0
  - matplotlib-base=3.8.0=py310h1128e8f_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - menuinst=2.0.2=py310hff52083_0
  - mkl=2023.2.0=h84fe81f_50496
  - ml_dtypes=0.2.0=py310hcc13569_2
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h9458935_1
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msgpack-python=1.0.7=py310hd41b1e2_0
  - multidict=6.0.5=py310h2372a71_0
  - munkres=1.1.4=py_0
  - nccl=2.21.5.1=h3a97aeb_0
  - ncurses=6.4.20240210=h59595ed_0
  - networkx=3.3=pyhd8ed1ab_1
  - numba=0.59.1=py310h7dc5dd1_0
  - numpy=1.24.4=py310ha4c1d20_0
  - nvcomp=3.0.6=h10b603f_0
  - nvtx=0.2.10=py310h2372a71_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.2.1=hd590300_1
  - opt_einsum=3.3.0=pyhc1e730c_2
  - orc=1.9.2=h4b38347_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=1.5.3=py310h9b08913_1
  - partd=1.4.1=pyhd8ed1ab_0
  - pillow=10.3.0=py310hf73ecf8_0
  - pip=24.0=pyhd8ed1ab_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - pluggy=1.4.0=pyhd8ed1ab_0
  - protobuf=4.24.4=py310h620c231_0
  - psutil=5.9.8=py310h2372a71_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyarrow=14.0.2=py310hf9e7431_3_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pyasn1=0.5.1=pyhd8ed1ab_0
  - pyasn1-modules=0.3.0=pyhd8ed1ab_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py310h2372a71_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_1
  - pylibraft=24.02.00=cuda12_py310_240212_g698d6c7b_0
  - pynvjitlink=0.1.14=py310hdaa3023_0
  - pynvml=11.4.1=pyhd8ed1ab_0
  - pyopenssl=24.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.14=hd12c33a_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-flatbuffers=24.3.25=pyh59ac667_0
  - python_abi=3.10=4_cp310
  - pytorch=2.1.2=cuda120_py310h8a81058_300
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytz=2024.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0.1=py310h2372a71_1
  - raft-dask=24.02.00=cuda12_py310_240212_g698d6c7b_0
  - rapids-dask-dependency=24.02.00=0
  - rdma-core=51.0=hd3aeb46_0
  - re2=2023.09.01=h7f4b329_1
  - readline=8.2=h8228510_1
  - reproc=14.2.4.post0=hd590300_1
  - reproc-cpp=14.2.4.post0=h59595ed_1
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - rich=13.7.1=pyhd8ed1ab_0
  - rmm=24.02.00=cuda12_py310_240212_g09b406c1_0
  - rsa=4.9=pyhd8ed1ab_0
  - ruamel.yaml=0.18.6=py310h2372a71_0
  - ruamel.yaml.clib=0.2.8=py310h2372a71_0
  - s2n=1.4.1=h06160fa_0
  - scikit-learn=1.3.0=py310h1128e8f_1
  - scipy=1.13.0=py310hb13e2d6_0
  - seaborn=0.12.2=py310h06a4308_0
  - setuptools=69.2.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - snappy=1.1.10=hdb0a2a9_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - spdlog=1.12.0=hd2e6256_2
  - sympy=1.12=pypyh9d50eac_103
  - tbb=2021.11.0=h00ab1b0_1
  - tblib=3.0.0=pyhd8ed1ab_0
  - tensorboard=2.15.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py310h75e40e8_1
  - tensorflow=2.15.0=cuda120py310h9360858_3
  - tensorflow-base=2.15.0=cuda120py310heceb7ac_3
  - tensorflow-estimator=2.15.0=cuda120py310h549c77d_3
  - termcolor=2.4.0=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.13=noxft_h4845f30_101
  - toolz=0.12.1=pyhd8ed1ab_0
  - tornado=6.4=py310h2372a71_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - treelite=4.0.0=py310h4a6579d_0
  - truststore=0.8.0=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - ucx=1.15.0=hda83522_8
  - ucx-proc=1.0.0=gpu
  - ucx-py=0.36.00=py310_240212_g1266b48_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - werkzeug=3.0.2=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - wrapt=1.14.1=py310h5764c6d_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xyzservices=2024.4.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.8.0=h59595ed_0
  - yarl=1.9.4=py310h2372a71_0
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zstandard=0.22.0=py310h1275a96_0
  - zstd=1.5.5=hfc55251_0
  - pip:
      - facenet-pytorch==2.5.3
      - latextable==1.0.1
      - netaddr==1.2.1
      - netifaces==0.11.0
      - texttable==1.7.0
